site_name: LLM-IE Documentation
theme:
    name: material
repo_url: https://github.com/daviden1013/llm-ie
repo_name: daviden1013/llm-ie

nav:
    - 'Home': 'index.md'
    - 'Installation': 'installation.md'
    - 'Quick Start': 'quick_start.md'
    - 'Web Application': 'web_application.md'
    - 'User Guide': 
      - 'LLM Configuration': 'llm_config.md'
      - 'LLM Inference Engine': 'llm_inference_engine.md'
      - 'Prompt Templates': 'prompt_templates.md'
      - 'Prompt Editor': 'prompt_editor.md'
      - 'Extractors': 'extractors.md'
      - 'Visualization': 'visualization.md'
      
    - 'API Reference': 
        - 'LLM Configuration': 'api/llm_config.md'
        - 'LLM Inference Engine': 'api/llm_inference_engine.md'
        - 'Extractors': 'api/extractors.md'
        - 'Chunkers': 'api/chunkers.md'
        - 'Prompt Editor': 'api/prompt_editor.md'

plugins:
    - search 
    - mkdocstrings:
        handlers:
          python:
            options:
              docstring_style: numpy
              show_root_heading: true
              show_source: true 
              members_order: source 
              separate_signature: true
              show_signature_annotations: true
              show_docstring_annotations: true
              merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences