---
  run_name: sample_config
  model: <your_model_name>
  llm_config: <your_llm_config>
  system_prompt_dir: <your_system_prompt_path>
  prompt_temp_dir: <your_user_prompt_path>
  num_workers: <number_of_concurrent_document_workers>
  concurrent_batch_size: <max_concurrent_requests_per_document>
  max_concurrent_requests: <global_max_concurrent_requests_for_llm_engine>

  data_dir: <your_data_path>
  model: <your_model_name>
  llm_config: <your_llm_config>
  out_dir: <your_output_path>
  log_dir: <your_messages_log_path>